stages:
  - comment
  - main

comment:
  image: node:lts
  stage: comment
  only:
    - merge_requests
  script: npx -y changesets-gitlab comment

main:
  image: node:lts
  stage: main
  script:
    - npm install -g pnpm
    - pnpm i --frozen-lockfile
    - pnpm run build
    - pnpm run test
    - |
      if [ "$CI_COMMIT_BRANCH" = "master" ]; then
        npx changesets-gitlab
      fi
  variables:
    INPUT_PUBLISH: pnpm publish -r --no-git-checks
